export const tokens = {
  colors: {
    background: {
      DEFAULT: '#F7F9FB',
      onBackground: '#191C1E',
    },
    surface: {
      background: '#F7F9FB',
      white: '#FFFFFF',
      dim: '#D8DADC',
      bright: '#F7F9FB',
      tint: '#515F78',
      variant: '#E0E3E5',
      onSurface: '#191C1E',
      onSurfaceVariant: '#44474D',
      inverse: {
        surface: '#2D3133',
        onSurface: '#EFF1F3',
      },
      container: {
        lowest: '#FFFFFF',
        low: '#F2F4F6',
        DEFAULT: '#ECEEF0',
        high: '#E6E8EA',
        highest: '#E0E3E5',
      },
    },
    primary: {
      DEFAULT: '#0D1C32',
      onPrimary: '#FFFFFF',
      container: '#0D1C32',
      onContainer: '#76849F',
      inverse: '#B9C7E4',
      fixed: '#D6E3FF',
      fixedDim: '#B9C7E4',
      onFixed: '#0D1C32',
      onFixedVariant: '#39475F',
    },
    secondary: {
      DEFAULT: '#006C49',
      onSecondary: '#FFFFFF',
      container: '#6CF8BB',
      onContainer: '#00714D',
      fixed: '#6FFBBE',
      fixedDim: '#4EDEA3',
      onFixed: '#002113',
      onFixedVariant: '#005236',
    },
    tertiary: {
      container: '#0B1C30',
      onContainer: '#75859D',
      fixed: '#D3E4FE',
      fixedDim: '#B7C8E1',
      onFixed: '#0B1C30',
      onFixedVariant: '#38485D',
    },
    error: {
      DEFAULT: '#BA1A1A',
      onError: '#FFFFFF',
      container: '#FFDAD6',
      onContainer: '#93000A',
    },
    border: {
      DEFAULT: '#E2E8F0',
      variant: '#C5C6CD',
    },
    outline: {
      DEFAULT: '#75777E',
      variant: '#C5C6CD',
    },
    text: {
      primary: '#191C1E',
      secondary: '#64748B',
      muted: '#94A3B8',
    },
    status: {
      success: {
        bg: '#DCFCE7',
        text: '#166534',
        border: '#BBF7D0',
      },
      neutral: {
        bg: '#F1F5F9',
        text: '#475569',
        border: '#E2E8F0',
      },
      error: {
        bg: '#FEE2E2',
        text: '#991B1B',
        border: '#FECACA',
      },
      warning: {
        bg: '#FEF3C7',
        text: '#92400E',
        border: '#FDE68A',
      },
      info: {
        bg: '#DBEAFE',
        text: '#1E40AF',
        border: '#BFDBFE',
      },
    },
    hover: {
      surface: '#F1F5F9',
      primary: '#162842',
    },
  },
  typography: {
    displayLg: {
      fontFamily: 'Inter',
      fontSize: '48px',
      fontWeight: '700',
      lineHeight: '56px',
      letterSpacing: '-0.02em',
    },
    headlineLg: {
      fontFamily: 'Inter',
      fontSize: '32px',
      fontWeight: '600',
      lineHeight: '40px',
      letterSpacing: '-0.01em',
    },
    headlineLgMobile: {
      fontFamily: 'Inter',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '32px',
    },
    headlineMd: {
      fontFamily: 'Inter',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '32px',
    },
    titleMd: {
      fontFamily: 'Inter',
      fontSize: '18px',
      fontWeight: '600',
      lineHeight: '24px',
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '24px',
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '20px',
    },
    labelMd: {
      fontFamily: 'JetBrains Mono',
      fontSize: '12px',
      fontWeight: '500',
      lineHeight: '16px',
      letterSpacing: '0.05em',
    },
    caption: {
      fontFamily: 'Inter',
      fontSize: '12px',
      fontWeight: '500',
      lineHeight: '16px',
    },
    fontFamily: {
      sans: ['Inter', 'system-ui', 'sans-serif'],
      mono: ['JetBrains Mono', 'monospace'],
    },
  },
  borderRadius: {
    sm: '0.125rem',
    DEFAULT: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    full: '9999px',
  },
  spacing: {
    base: '4px',
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    '2xl': '48px',
    '3xl': '64px',
    gutter: '24px',
    marginMobile: '16px',
    marginDesktop: '40px',
  },
  shadows: {
    subtle: '0px 4px 12px rgba(10, 25, 47, 0.08)',
    card: '0 1px 3px 0 rgba(0, 0, 0, 0.06), 0 1px 2px -1px rgba(0, 0, 0, 0.06)',
    modal: '0px 4px 12px rgba(10, 25, 47, 0.08)',
  },
  grid: {
    desktop: 12,
    tablet: 8,
    mobile: 4,
  },
} as const;

export type DesignTokens = typeof tokens;
