import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "on-surface-variant": "#44474d",
        "on-primary-container": "#76849f",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-container": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b9c7e4",
        "on-secondary-fixed": "#002113",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        tertiary: "#000000",
        "primary-container": "#0d1c32",
        surface: "#f7f9fb",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-highest": "#e0e3e5",
        secondary: "#006c49",
        "inverse-primary": "#b9c7e4",
        "secondary-fixed": "#6ffbbe",
        "on-background": "#191c1e",
        background: "#f7f9fb",
        outline: "#75777e",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#515f78",
        "outline-variant": "#c5c6cd",
        "on-primary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "secondary-fixed-dim": "#4edea3",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#39475f",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0d1c32",
        primary: "#000000",
        "on-tertiary-fixed-variant": "#38485d",
        "on-secondary-container": "#00714d",
        "on-tertiary-container": "#75859d",
        "tertiary-fixed-dim": "#b7c8e1",
        "primary-fixed": "#d6e3ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        md: "16px",
        xl: "32px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        lg: "24px",
        "3xl": "64px",
        base: "4px",
        xs: "4px",
        gutter: "24px",
        "2xl": "48px",
      },
      fontFamily: {
        "title-md": ["Inter"],
        "body-lg": ["Inter"],
        caption: ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["JetBrains Mono"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
